from pathlib import Path
import textwrap

ROOT = Path.cwd()

files = {'.codex/config.toml': 'model = "gpt-5.5"\n'
                       'model_provider = "openai"\n'
                       'model_reasoning_effort = "medium"\n'
                       'model_verbosity = "medium"\n'
                       '\n'
                       'approval_policy = "on-request"\n'
                       'sandbox_mode = "workspace-write"\n'
                       '\n'
                       'project_root_markers = [".git", "pyproject.toml", "package.json", "AGENTS.md"]\n'
                       '\n'
                       'tool_output_token_limit = 12000\n'
                       'model_auto_compact_token_limit = 64000\n'
                       '\n'
                       '[features]\n'
                       'codex_hooks = true\n'
                       '\n'
                       '[profiles.plan]\n'
                       'approval_policy = "on-request"\n'
                       'sandbox_mode = "read-only"\n'
                       'model_reasoning_effort = "high"\n'
                       'model_verbosity = "low"\n'
                       '\n'
                       '[profiles.lean]\n'
                       'approval_policy = "on-request"\n'
                       'sandbox_mode = "workspace-write"\n'
                       'model_reasoning_effort = "medium"\n'
                       'model_verbosity = "medium"\n'
                       '\n'
                       '[profiles.ship]\n'
                       'approval_policy = "on-request"\n'
                       'sandbox_mode = "workspace-write"\n'
                       'model_reasoning_effort = "high"\n'
                       'model_verbosity = "medium"\n'
                       '\n'
                       '[agents]\n'
                       'max_threads = 4\n'
                       'max_depth = 1\n'
                       '\n'
                       '[agents.planner]\n'
                       'description = "Break the task into bounded steps, identify risks, and define the completion '
                       'contract."\n'
                       'config_file = "agents/planner.toml"\n'
                       '\n'
                       '[agents.implementer]\n'
                       'description = "Make minimal code changes according to the plan. Avoid broad rewrites."\n'
                       'config_file = "agents/implementer.toml"\n'
                       '\n'
                       '[agents.reviewer]\n'
                       'description = "Review diffs for architecture violations, hidden test weakening, security '
                       'issues, and incomplete validation."\n'
                       'config_file = "agents/reviewer.toml"\n'
                       '\n'
                       '[agents.tester]\n'
                       'description = "Run focused validation, inspect failures, and separate pre-existing failures '
                       'from introduced failures."\n'
                       'config_file = "agents/tester.toml"\n',
 '.codex/hooks.json': '{\n'
                      '  "hooks": {\n'
                      '    "PreToolUse": [\n'
                      '      {\n'
                      '        "matcher": "Bash",\n'
                      '        "hooks": [\n'
                      '          {\n'
                      '            "type": "command",\n'
                      '            "command": "python .codex/hooks/pre_tool_use_policy.py",\n'
                      '            "timeout": 10,\n'
                      '            "statusMessage": "Checking command safety"\n'
                      '          }\n'
                      '        ]\n'
                      '      }\n'
                      '    ],\n'
                      '    "PostToolUse": [\n'
                      '      {\n'
                      '        "matcher": "apply_patch|Edit|Write|MultiEdit",\n'
                      '        "hooks": [\n'
                      '          {\n'
                      '            "type": "command",\n'
                      '            "command": "python .codex/hooks/post_edit_validate.py",\n'
                      '            "timeout": 90,\n'
                      '            "statusMessage": "Running edit validation"\n'
                      '          }\n'
                      '        ]\n'
                      '      }\n'
                      '    ],\n'
                      '    "PermissionRequest": [\n'
                      '      {\n'
                      '        "matcher": "Bash",\n'
                      '        "hooks": [\n'
                      '          {\n'
                      '            "type": "command",\n'
                      '            "command": "python .codex/hooks/pre_commit_check.py",\n'
                      '            "timeout": 30,\n'
                      '            "statusMessage": "Reviewing permission request"\n'
                      '          }\n'
                      '        ]\n'
                      '      }\n'
                      '    ],\n'
                      '    "Stop": [\n'
                      '      {\n'
                      '        "hooks": [\n'
                      '          {\n'
                      '            "type": "command",\n'
                      '            "command": "python .codex/hooks/summarize_session.py",\n'
                      '            "timeout": 30,\n'
                      '            "statusMessage": "Updating Codex handoff"\n'
                      '          }\n'
                      '        ]\n'
                      '      }\n'
                      '    ]\n'
                      '  }\n'
                      '}\n',
 '.codex/handoff.md': '# Codex Handoff\n'
                      '\n'
                      '## Current Goal\n'
                      '- None yet.\n'
                      '\n'
                      '## Current Branch / Worktree\n'
                      '- Unknown.\n'
                      '\n'
                      '## Files Touched\n'
                      '- None.\n'
                      '\n'
                      '## Decisions Made\n'
                      '- None.\n'
                      '\n'
                      '## Validation Run\n'
                      '- None.\n'
                      '\n'
                      '## Known Failures\n'
                      '- None.\n'
                      '\n'
                      '## Next Exact Step\n'
                      '1. Define task.\n'
                      '2. Make minimal change.\n'
                      '3. Run focused validation.\n'
                      '\n'
                      '## Do Not Repeat\n'
                      '- Do not weaken tests to pass.\n'
                      '- Do not mix refactor and behavior change unless explicitly requested.\n'
                      '- Do not read all docs blindly.\n'
                      '- Do not break layer boundaries.\n',
 '.codex/memory.md': '# Codex Project Memory\n'
                     '\n'
                     '## Ratchet Rules\n'
                     'Every repeated Codex failure becomes a permanent rule here, in `AGENTS.md`, in '
                     '`docs/codex/index.md`, or in a hook.\n'
                     '\n'
                     '## Existing Project Navigation\n'
                     '- Keep root `AGENTS.md` as the navigation index.\n'
                     '- Codex must read `docs/codex/index.md` after `AGENTS.md`.\n'
                     '- Do not overwrite root `AGENTS.md`.\n'
                     '- Use matching layer docs only.\n'
                     '- Do not read all docs blindly.\n'
                     '\n'
                     '## Known Project Constraints\n'
                     '- Pipeline invariant: collect → analyze → state → output → store → log.\n'
                     '- External data belongs in collector.\n'
                     '- LLM logic belongs in analyzer.\n'
                     '- Portfolio and signal state must stay reproducible and avoid external deps.\n'
                     '- Output formatting should be deterministic with minimal diffs.\n'
                     '- Storage must go through datastore.\n'
                     '- Logging must record pipeline events.\n'
                     '- Cost target: under $5/month unless explicitly changed.\n'
                     '- Non-goals: no real-time systems, no trading automation, no complex infra.\n'
                     '\n'
                     '## Codex Harness Rules\n'
                     '1. Work in small, verifiable steps: plan → edit → validate → summarize.\n'
                     '2. Before editing, state the intended change in 3-7 lines.\n'
                     '3. Do not comment out, delete, or weaken tests to make them pass.\n'
                     '4. Do not hide failures.\n'
                     '5. Separate pre-existing failures from introduced failures.\n'
                     '6. Do not perform large changes directly on `main`.\n'
                     '7. Ask before destructive operations: file deletion, force-push, reset --hard, migration, '
                     'dependency replacement.\n'
                     '8. After editing code, run the smallest relevant validation command.\n'
                     '9. Before finishing, report changed files, validation commands, failures, risks, and next step.\n'
                     '\n'
                     '## Useful Commands\n'
                     '```bash\n'
                     'python -m compileall main.py src tests\n'
                     'python -m unittest discover -s tests -v\n'
                     'python -m src.cli.run_sectors\n'
                     'cd web && npm run build\n'
                     '```\n'
                     '\n'
                     '## Past Failures\n'
                     '- None yet.\n',
 '.codex/contracts/sprint-contract.md': '# Sprint Contract\n'
                                        '\n'
                                        '## Goal\n'
                                        'State the exact deliverable in one sentence.\n'
                                        '\n'
                                        '## In Scope\n'
                                        '- Smallest code path needed for the requested change.\n'
                                        '- Tests or validation directly related to the change.\n'
                                        '- Documentation update if behavior, contracts, routing, or outputs changed.\n'
                                        '\n'
                                        '## Out of Scope\n'
                                        '- Large unrelated refactors.\n'
                                        '- Dependency replacement.\n'
                                        '- Silent architecture changes.\n'
                                        '- Test weakening.\n'
                                        '- Real-time systems.\n'
                                        '- Trading automation.\n'
                                        '- Complex infra.\n'
                                        '\n'
                                        '## Definition of Done\n'
                                        '- Code compiles.\n'
                                        '- Relevant tests or build commands were run.\n'
                                        '- Failures are classified.\n'
                                        '- Diff is summarized.\n'
                                        '- Related docs are updated if behavior changed.\n'
                                        '- Next step is explicit.\n'
                                        '\n'
                                        '## Stop Conditions\n'
                                        'Stop and report if:\n'
                                        '- Required file or dependency is missing.\n'
                                        '- Baseline tests fail before changes.\n'
                                        '- The change requires destructive git/database operations.\n'
                                        '- The task expands beyond the original scope.\n',
 '.codex/hooks/pre_tool_use_policy.py': 'import json\n'
                                        'import re\n'
                                        'import sys\n'
                                        '\n'
                                        '\n'
                                        'def deny(reason: str) -> None:\n'
                                        '    print(json.dumps({\n'
                                        '        "hookSpecificOutput": {\n'
                                        '            "hookEventName": "PreToolUse",\n'
                                        '            "permissionDecision": "deny",\n'
                                        '            "permissionDecisionReason": reason\n'
                                        '        }\n'
                                        '    }))\n'
                                        '    sys.exit(0)\n'
                                        '\n'
                                        '\n'
                                        'def allow() -> None:\n'
                                        '    print(json.dumps({}))\n'
                                        '    sys.exit(0)\n'
                                        '\n'
                                        '\n'
                                        'try:\n'
                                        '    payload = json.load(sys.stdin)\n'
                                        'except Exception:\n'
                                        '    payload = {}\n'
                                        '\n'
                                        'tool_input = payload.get("tool_input", {}) or {}\n'
                                        'cmd = tool_input.get("command", "") or ""\n'
                                        '\n'
                                        'blocked_patterns = [\n'
                                        '    (r"\\brm\\s+-rf\\s+[/~]", "Refusing dangerous rm -rf target."),\n'
                                        '    (r"\\bgit\\s+push\\s+--force\\b", "Refusing force push."),\n'
                                        '    (r"\\bgit\\s+reset\\s+--hard\\b", "Refusing git reset --hard."),\n'
                                        '    (r"\\bgit\\s+clean\\s+-fdx\\b", "Refusing destructive git clean."),\n'
                                        '    (r"\\bnpm\\s+publish\\b", "Refusing npm publish."),\n'
                                        '    (r"\\bpip\\s+install\\b.*--break-system-packages", "Refusing unsafe pip '
                                        'install."),\n'
                                        '    (r"\\bcurl\\b.*\\|\\s*(sh|bash|zsh|powershell|pwsh)\\b", "Refusing '
                                        'pipe-to-shell install."),\n'
                                        '    (r"\\bwget\\b.*\\|\\s*(sh|bash|zsh|powershell|pwsh)\\b", "Refusing '
                                        'pipe-to-shell install."),\n'
                                        '    (r"\\bRemove-Item\\b.*\\s-Recurse\\b.*\\s-Force\\b", "Refusing recursive '
                                        'forced deletion."),\n'
                                        ']\n'
                                        '\n'
                                        'for pattern, reason in blocked_patterns:\n'
                                        '    if re.search(pattern, cmd, flags=re.IGNORECASE):\n'
                                        '        deny(f"{reason}\\nCommand: {cmd}")\n'
                                        '\n'
                                        'risky_patterns = [\n'
                                        '    r"\\balembic\\s+upgrade\\b",\n'
                                        '    r"\\bprisma\\s+migrate\\b",\n'
                                        '    r"\\bdrop\\s+table\\b",\n'
                                        '    r"\\bdelete\\s+from\\b",\n'
                                        '    r"\\btruncate\\s+table\\b",\n'
                                        ']\n'
                                        '\n'
                                        'for pattern in risky_patterns:\n'
                                        '    if re.search(pattern, cmd, flags=re.IGNORECASE):\n'
                                        '        deny(f"Database/migration-like command requires manual '
                                        'review.\\nCommand: {cmd}")\n'
                                        '\n'
                                        'allow()\n',
 '.codex/hooks/post_edit_validate.py': 'import json\n'
                                       'import subprocess\n'
                                       'import sys\n'
                                       'from pathlib import Path\n'
                                       '\n'
                                       '\n'
                                       'def find_repo_root() -> Path:\n'
                                       '    cur = Path.cwd()\n'
                                       '    for p in [cur, *cur.parents]:\n'
                                       '        if (p / ".git").exists() or (p / "AGENTS.md").exists():\n'
                                       '            return p\n'
                                       '    return cur\n'
                                       '\n'
                                       '\n'
                                       'ROOT = find_repo_root()\n'
                                       '\n'
                                       '\n'
                                       'def run(cmd: str, timeout: int = 60):\n'
                                       '    try:\n'
                                       '        p = subprocess.run(\n'
                                       '            cmd,\n'
                                       '            cwd=ROOT,\n'
                                       '            shell=True,\n'
                                       '            text=True,\n'
                                       '            stdout=subprocess.PIPE,\n'
                                       '            stderr=subprocess.STDOUT,\n'
                                       '            timeout=timeout,\n'
                                       '        )\n'
                                       '        return p.returncode, p.stdout[-6000:]\n'
                                       '    except subprocess.TimeoutExpired as e:\n'
                                       '        return 124, f"Command timed out: {cmd}\\n{e}"\n'
                                       '\n'
                                       '\n'
                                       'def block(reason: str) -> None:\n'
                                       '    print(json.dumps({\n'
                                       '        "decision": "block",\n'
                                       '        "reason": reason,\n'
                                       '        "hookSpecificOutput": {\n'
                                       '            "hookEventName": "PostToolUse",\n'
                                       '            "additionalContext": reason\n'
                                       '        }\n'
                                       '    }))\n'
                                       '    sys.exit(0)\n'
                                       '\n'
                                       '\n'
                                       'checks = []\n'
                                       '\n'
                                       'if (ROOT / "main.py").exists() or (ROOT / "src").exists():\n'
                                       '    checks.append("python -m compileall main.py src tests")\n'
                                       '\n'
                                       'if (ROOT / "web" / "package.json").exists():\n'
                                       '    checks.append("cd web && npm run --silent lint --if-present")\n'
                                       '\n'
                                       'failures = []\n'
                                       '\n'
                                       'for cmd in checks:\n'
                                       '    code, out = run(cmd, timeout=90)\n'
                                       '    if code != 0:\n'
                                       '        failures.append(f"$ {cmd}\\n{out}")\n'
                                       '\n'
                                       'if failures:\n'
                                       '    block(\n'
                                       '        "Fast validation failed after edit. Fix this before '
                                       'continuing.\\n\\n"\n'
                                       '        + "\\n\\n---\\n\\n".join(failures)\n'
                                       '    )\n'
                                       '\n'
                                       'print(json.dumps({}))\n'
                                       'sys.exit(0)\n',
 '.codex/hooks/pre_commit_check.py': 'import json\n'
                                     'import re\n'
                                     'import sys\n'
                                     '\n'
                                     '\n'
                                     'def deny(message: str) -> None:\n'
                                     '    print(json.dumps({\n'
                                     '        "hookSpecificOutput": {\n'
                                     '            "hookEventName": "PermissionRequest",\n'
                                     '            "decision": {\n'
                                     '                "behavior": "deny",\n'
                                     '                "message": message\n'
                                     '            }\n'
                                     '        }\n'
                                     '    }))\n'
                                     '    sys.exit(0)\n'
                                     '\n'
                                     '\n'
                                     'try:\n'
                                     '    payload = json.load(sys.stdin)\n'
                                     'except Exception:\n'
                                     '    payload = {}\n'
                                     '\n'
                                     'tool_input = payload.get("tool_input", {}) or {}\n'
                                     'cmd = tool_input.get("command", "") or ""\n'
                                     'desc = tool_input.get("description", "") or ""\n'
                                     '\n'
                                     'deny_patterns = [\n'
                                     '    r"\\bgit\\s+push\\s+--force\\b",\n'
                                     '    r"\\bgit\\s+reset\\s+--hard\\b",\n'
                                     '    r"\\bgit\\s+clean\\s+-fdx\\b",\n'
                                     '    r"\\bnpm\\s+publish\\b",\n'
                                     '    r"\\bpypi\\b.*publish",\n'
                                     ']\n'
                                     '\n'
                                     'for pat in deny_patterns:\n'
                                     '    if re.search(pat, cmd, re.IGNORECASE) or re.search(pat, desc, '
                                     're.IGNORECASE):\n'
                                     '        deny(f"Denied by repository policy.\\nCommand: {cmd}\\nReason: {desc}")\n'
                                     '\n'
                                     'print(json.dumps({}))\n'
                                     'sys.exit(0)\n',
 '.codex/hooks/summarize_session.py': 'import json\n'
                                      'import subprocess\n'
                                      'import sys\n'
                                      'from datetime import datetime\n'
                                      'from pathlib import Path\n'
                                      '\n'
                                      '\n'
                                      'def find_repo_root() -> Path:\n'
                                      '    cur = Path.cwd()\n'
                                      '    for p in [cur, *cur.parents]:\n'
                                      '        if (p / ".git").exists() or (p / "AGENTS.md").exists():\n'
                                      '            return p\n'
                                      '    return cur\n'
                                      '\n'
                                      '\n'
                                      'ROOT = find_repo_root()\n'
                                      'HANDOFF = ROOT / ".codex" / "handoff.md"\n'
                                      '\n'
                                      '\n'
                                      'def sh(cmd: str) -> str:\n'
                                      '    try:\n'
                                      '        p = subprocess.run(\n'
                                      '            cmd,\n'
                                      '            shell=True,\n'
                                      '            cwd=ROOT,\n'
                                      '            text=True,\n'
                                      '            stdout=subprocess.PIPE,\n'
                                      '            stderr=subprocess.STDOUT,\n'
                                      '            timeout=10,\n'
                                      '        )\n'
                                      '        return p.stdout.strip()\n'
                                      '    except Exception as e:\n'
                                      '        return f"unavailable: {e}"\n'
                                      '\n'
                                      '\n'
                                      'try:\n'
                                      '    payload = json.load(sys.stdin)\n'
                                      'except Exception:\n'
                                      '    payload = {}\n'
                                      '\n'
                                      'last_msg = payload.get("last_assistant_message") or ""\n'
                                      '\n'
                                      'branch = sh("git branch --show-current")\n'
                                      'status = sh("git status --short")\n'
                                      'changed = sh("git diff --name-only")\n'
                                      '\n'
                                      'content = f"""# Codex Handoff\n'
                                      '\n'
                                      '## Updated\n'
                                      '{datetime.now().isoformat(timespec="seconds")}\n'
                                      '\n'
                                      '## Current Branch / Worktree\n'
                                      '{branch or "unknown"}\n'
                                      '\n'
                                      '## Files Touched\n'
                                      '{changed or "None"}\n'
                                      '\n'
                                      '## Git Status\n'
                                      '```text\n'
                                      '{status or "clean"}\n'
                                      '```\n'
                                      '\n'
                                      '## Last Assistant Message\n'
                                      '```text\n'
                                      '{last_msg[-3000:] if last_msg else "None"}\n'
                                      '```\n'
                                      '\n'
                                      '## Next Exact Step\n'
                                      '1. Review git diff.\n'
                                      '2. Run focused validation.\n'
                                      '3. Separate pre-existing failures from introduced failures.\n'
                                      '4. Update related docs if behavior, routing, contracts, or outputs changed.\n'
                                      '"""\n'
                                      '\n'
                                      'HANDOFF.parent.mkdir(parents=True, exist_ok=True)\n'
                                      'HANDOFF.write_text(content, encoding="utf-8")\n'
                                      '\n'
                                      'print(json.dumps({}))\n'
                                      'sys.exit(0)\n',
 '.codex/skills/bugfix/SKILL.md': '---\n'
                                  'name: bugfix\n'
                                  'description: Use when fixing a failing test, runtime error, import error, or broken '
                                  'behavior.\n'
                                  '---\n'
                                  '\n'
                                  '# Bugfix Skill\n'
                                  '\n'
                                  '## Workflow\n'
                                  '1. Reproduce or locate the failure.\n'
                                  '2. Identify the smallest responsible code path.\n'
                                  '3. Make the minimal fix.\n'
                                  '4. Add or update a focused test if possible.\n'
                                  '5. Run the smallest relevant validation.\n'
                                  '6. Report whether the failure was pre-existing or introduced.\n'
                                  '\n'
                                  '## Rules\n'
                                  '- Do not rewrite unrelated code.\n'
                                  '- Do not weaken tests.\n'
                                  '- Do not change public behavior unless necessary.\n'
                                  '- If baseline is already broken, record it before editing.\n',
 '.codex/skills/refactor/SKILL.md': '---\n'
                                    'name: refactor\n'
                                    'description: Use when improving structure without intentionally changing '
                                    'behavior.\n'
                                    '---\n'
                                    '\n'
                                    '# Refactor Skill\n'
                                    '\n'
                                    '## Workflow\n'
                                    '1. State the behavior that must remain unchanged.\n'
                                    '2. Identify the smallest refactor boundary.\n'
                                    '3. Move or simplify code in small steps.\n'
                                    '4. Run validation after each meaningful step.\n'
                                    '5. Summarize behavior-preservation evidence.\n'
                                    '\n'
                                    '## Rules\n'
                                    '- Do not mix feature work with refactor.\n'
                                    '- Keep public APIs stable unless asked.\n'
                                    '- Avoid broad renames unless they reduce real ambiguity.\n'
                                    '- If tests are missing, use compile/build validation at minimum.\n',
 '.codex/skills/frontend/SKILL.md': '---\n'
                                    'name: frontend\n'
                                    'description: Use when editing React, UI, CSS, charts, dashboard layout, or visual '
                                    'components.\n'
                                    '---\n'
                                    '\n'
                                    '# Frontend Skill\n'
                                    '\n'
                                    '## Workflow\n'
                                    '1. Preserve existing data flow and props unless asked.\n'
                                    '2. Improve visual hierarchy, spacing, contrast, and empty states.\n'
                                    '3. Keep components small and readable.\n'
                                    '4. Run lint/build if available.\n'
                                    '5. Report any unverified browser behavior.\n'
                                    '\n'
                                    '## UI Rules\n'
                                    '- Prioritize readability over decorative complexity.\n'
                                    '- Avoid breaking responsive layout.\n'
                                    '- Avoid hardcoded fake financial values unless explicitly mocking.\n'
                                    '- Keep chart semantics clear: labels, units, and time ranges.\n',
 '.codex/skills/stock-pipeline/SKILL.md': '---\n'
                                          'name: stock-pipeline\n'
                                          'description: Use when modifying stock research pipeline, sector scan, '
                                          'collector, analyzer, decision, state, datastore, output, YAML ticker lists, '
                                          'or LLM cost settings.\n'
                                          '---\n'
                                          '\n'
                                          '# Stock Pipeline Skill\n'
                                          '\n'
                                          '## Required Navigation\n'
                                          '1. Read root `AGENTS.md`.\n'
                                          '2. Read `docs/codex/index.md`.\n'
                                          '3. Open only the matching layer docs for the task.\n'
                                          '\n'
                                          '## Pipeline Invariant\n'
                                          'collect → analyze → state → output → store → log\n'
                                          '\n'
                                          '## Layer Rules\n'
                                          '1. collector: external data only, approved sources, fallback chains.\n'
                                          '2. analyzer: LLM logic, deterministic prompts, structured output, '
                                          'minimize/batch calls.\n'
                                          '3. decision: factor scoring and conviction.\n'
                                          '4. state: portfolio and signals, reproducible, no external deps.\n'
                                          '5. output: deterministic formatting, minimal diffs.\n'
                                          '6. datastore: all persistence goes through it.\n'
                                          '7. logging: record all pipeline events.\n'
                                          '8. utils: shared helpers only.\n'
                                          '\n'
                                          '## Hard Rules\n'
                                          '- Do not read all docs blindly.\n'
                                          '- Do not break layer boundaries.\n'
                                          '- Do not add real-time systems.\n'
                                          '- Do not add trading automation.\n'
                                          '- Do not add complex infra.\n'
                                          '- Keep cost unchanged unless explicitly asked.\n'
                                          '- YAML ticker changes must avoid duplicates and preserve sector balance.\n'
                                          '- LLM cost/config changes must include a short rationale.\n'
                                          '\n'
                                          '## Validation\n'
                                          'Run at least:\n'
                                          '```bash\n'
                                          'python -m compileall main.py src tests\n'
                                          '```\n'
                                          '\n'
                                          'When relevant:\n'
                                          '```bash\n'
                                          'python -m unittest discover -s tests -v\n'
                                          'python -m src.cli.run_sectors\n'
                                          'cd web && npm run build\n'
                                          '```\n',
 '.codex/agents/planner.toml': 'name = "planner"\n'
                               'description = "Break the task into bounded steps, identify risks, and define the completion contract."\n'
                               'model = "gpt-5.5"\n'
                               'model_reasoning_effort = "high"\n'
                               'model_verbosity = "low"\n'
                               '\n'
                               'developer_instructions = """\n'
                               'You are the planner. Do not edit files.\n'
                               'Read AGENTS.md first, then docs/codex/index.md if relevant.\n'
                               'Produce a bounded plan, risks, and definition of done.\n'
                               'Keep the plan small enough for one worktree session.\n'
                               'Do not recommend reading all docs blindly.\n'
                               '"""\n',
 '.codex/agents/implementer.toml': 'name = "implementer"\n'
                                   'description = "Make minimal code changes according to the plan. Avoid broad rewrites."\n'
                                   'model = "gpt-5.5"\n'
                                   'model_reasoning_effort = "medium"\n'
                                   'model_verbosity = "medium"\n'
                                   '\n'
                                   'developer_instructions = """\n'
                                   'You are the implementer. Make minimal changes only.\n'
                                   'Read only the matching layer docs.\n'
                                   'Do not broaden scope. Do not weaken tests.\n'
                                   'Prefer small diffs over clever rewrites.\n'
                                   'Update related docs when behavior, contracts, routing, or outputs change.\n'
                                   '"""\n',
 '.codex/agents/reviewer.toml': 'name = "reviewer"\n'
                                'description = "Review diffs for architecture violations, hidden test weakening, security issues, and incomplete validation."\n'
                                'model = "gpt-5.5"\n'
                                'model_reasoning_effort = "high"\n'
                                'model_verbosity = "medium"\n'
                                '\n'
                                'developer_instructions = """\n'
                                'You are the reviewer. Inspect the diff for:\n'
                                '- architecture boundary violations\n'
                                '- hidden test weakening\n'
                                '- unsafe shell/git/database operations\n'
                                '- missing validation\n'
                                '- overbroad changes\n'
                                '- missing docs updates\n'
                                '- cost increases\n'
                                'Return concrete findings and required fixes.\n'
                                '"""\n',
 '.codex/agents/tester.toml': 'name = "tester"\n'
                              'description = "Run focused validation, inspect failures, and separate pre-existing failures from introduced failures."\n'
                              'model = "gpt-5.5"\n'
                              'model_reasoning_effort = "medium"\n'
                              'model_verbosity = "low"\n'
                              '\n'
                              'developer_instructions = """\n'
                              'You are the tester. Run or recommend focused validation.\n'
                              'Classify failures as pre-existing, introduced, flaky, or environment-related.\n'
                              'Do not modify production code unless explicitly asked.\n'
                              '"""\n'}

# Safety guard: never overwrite the existing project navigation file.
files.pop("AGENTS.md", None)

for rel, content in files.items():
    path = ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(textwrap.dedent(content).lstrip(), encoding="utf-8")

print("Created Codex harness files:")
for rel in files:
    print(f" - {rel}")

if (ROOT / "AGENTS.md").exists():
    print("\nKept existing AGENTS.md unchanged.")
else:
    print("\nWarning: AGENTS.md was not found. This harness expects your existing AGENTS.md navigation file.")
